### PR TITLE
Fix client example

### LINKED ISSUE #87: Fix client-example
Nothing is rendering in client-example due to TS not transpiling. The issue is actually because the way in which the component is exported has changed in procaptcha-react

### PR DESCRIPTION
**Pull request by forgetso**

### CODE REVIEW

File: dev/src/setup/provider.ts [hunk 1]
```diff
@@ -72,6 +72,8 @@ export async function setupProvider(env: ProsopoEnvironment, provider: IProvider
     } catch (e) {
         logger.warn(e)
     }
+    const registeredProvider = await env.contractInterface.getProviderDetails(provider.address)
+    console.log(registeredProvider)
```
Comment (goastler) [inline dev/src/setup/provider.ts]: left over debug?

**Review by goastler — DISMISSED** [review]

File: dev/src/setup/provider.ts (hunk 1 above)
Comment (forgetso) [reply dev/src/setup/provider.ts]: yep, removed

**Review by HughParry — APPROVED** [review]
